import { ContextProvider } from "@/component/context";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={"AskingPrompt-Body"}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
